### ISSUE TITLE
Establishing a coopertative of freelancers

### ISSUE THREAD

**Issue by rojkov** [sam-hosseini/freelancing-in-finland#17]
The howto could be extended to cover the case of freelancer cooperatives:
* registration;
* accounting and taxation;
* employing salesmen and/or an accountant by a cooperative;
* coop services applicable to freelancers (Pellervo?);
* best practices (more members bigger undertakings could be enabled for a cooperative,...).

**Comment by sam-hosseini** [comment]
I'm personally interested to understand cooperatives a lot more than what I know now, which is rather limited to a [lecture I watched on Youtube](https://www.youtube.com/watch?v=a1WUKahMm1s) and a small pdf about [worker co-ops for freelance companies](https://techworker.coop/sites/default/files/TechCoopHOWTO.pdf).

I would imagine the **most important benefit** of establishing such a thing would be the ability **to offer a team of developers**, which is sometimes required to win the big monies in public sector or bigger projects.

I'd love to hear everyone's input, thoughts, and comments :)

**Comment by cipy** [comment]
the risk / liability is shared in a cooperative, so maybe you don't want that 😸

**Comment by sam-hosseini** [comment]
@cipy what if each freelancer would have their own company and the co-operative would be a limited umberella company with which a **group** of freelancers can apply to a public project for example?

Then, each freelancer would invoice the umberella company with their share of the project. Keeping the liability to its minimum.
