### ISSUE TITLE
Including other ways to get started without setting up an Oy

### ISSUE THREAD

**Issue by olegp** [sam-hosseini/freelancing-in-finland#22]
Would it be worth mentioning other ways to get started as a freelancer other than setting up an Oy?

In order to work as a freelancer in Finland, you do not need to incorporate to begin with and you certainly don't need to set up an Oy right away. In fact doing so, can be counter productive, since while setting up a company is easy, shutting own down and becoming an employee again is not simple around here.

I'm running [Toughbyte](https://www.toughbyte.com/) and we act as one of the brokers for freelancers in Finland such as the ones mentioned in this guide. What I've been recommending to those wanting to go freelance is that they first try to become employed by a broker on a fixed term contract (which is something we've done on occasion) or work through a cooperative such as Eezy and Ukko (osuuskunta in Finnish). After that, they can set up an individual entrepreneurship (toiminimi) and only once they've had consistent revenue for about a year, consider setting up an Oy. The limited liability that an Oy provides isn't strictly speaking necessary when working as part of a team on a times and materials basis.

**Comment by sam-hosseini** [comment]
Hi Oleg and thanks for opening a discussion about an important subject 🚀

> Would it be worth mentioning other ways to get started as a freelancer other than setting up an Oy?

With respect, no. I'm putting my decision upon on the following 2 reasons:

1. The **target audience** of the guide from the beginning has been:

> You want to establish a limited liability company to offer your freelance services through it

Changing the target audience of the guide at this point would damage the **integrity and coherence** of the guide in my opinion.

2.  About:

>  The limited liability that an Oy provides isn't strictly speaking necessary when working as part of a team on a times and materials basis.

I have tried to be as little opinionated as possible when writing the guide. However, I think absolute unopinionatedness not only is hard to achieve as a human, but would result in the super-verbose guides most people wouldn't find the time or interest to read. Some opinion is necessary, and I'm of the opinion that if all the people who operate under a Toiminimi would know that:

* Their personal assetts will be taken from them if they damage the client and they are found liable.
* They no longer need to invest 2500€ share capital when establishing a company.
* It's **not** that difficult to operate a limited liability company.

Then, I think most people would think twice before going for a toiminimi over a limited company.
Also, in my opinion, **it's not about the (low) probobility of whether I need the limited liability, but the fact that if I need it IN A COURT ONE DAY, how disasterous it would be if I wouldn't have it?** 😅
