### ISSUE TITLE
even when you're an EU citizen, relocation is not given/free

### ISSUE THREAD

**Issue by cipy** [sam-hosseini/freelancing-in-finland#25]
You are not required to have a specific amount of money but _you must have enough funds to support yourself. Social assistance may not be your principal means of support_. We will take your personal circumstances into account when we consider this income requirement.

via https://migri.fi/en/registration-of-right-of-residence, first point 5.

**Comment by sam-hosseini** [comment]
Hi Ciprian! Thanks for pointing this out 👍🏼

I'm not sure whether you'd like me to make any changes to the guide based on this?

The reason I'm asking is that in the guide, it's written:

> If you're a EU citizen, **as the target audience of this guide is people who are already living in Finland for more than 3 months**, given that you have **already registered** your right of residence, you don't need to apply for another permit.

This essentially excludes any EU citizen from the scope of the guide who have not registered their right of residence.

**Comment by cipy** [comment]
Maybe it would be clearer to state: EU citizen who is already resident in
Finland

As that would imply that (s)he meets all requirements to stay and work in
Finland, including full benefits from Kela.

Living for more than 3 months is too generic IMHO. It could mean (s)he just
landed here, maybe the residence is still in question, as any EU citizen
can live here for 3 months, no questions asked.

Also, if (s)he just got in Finland 🇫🇮 on a work contract with a local
employer, hence legally allowed to stay more than 3 months, and then reads
your blog and says: so cool, I’ll resign now (month 4) and start my own
company and if things fall apart I’ll go to Kela — oh well, you need to
contribute to Kela for a certain period of time (1 year?) before you’re
granted full benefits.

I won’t create another issue, but your budget for the legal entity (at
least Oy) in Finland must include a €3000 fund to close the company if
that’s the case down the road. Yes, registration for Oy might be €300, but
de-registration is one year (I think) plus €3000.

Regards,

**Comment by sam-hosseini** [comment]
> but your budget for the legal entity (at least Oy) in Finland must include a €3000 fund to close the company if that’s the case down the road.

Could you please provide a reference for your claim? For closing down a limited liability company, according to PRH, either by [Liquidation](https://www.prh.fi/en/kaupparekisteri/lopettaminen/osakeyhtio/selvitystila.html) or [Deregistration](https://www.prh.fi/en/kaupparekisteri/lopettaminen/osakeyhtio/pakkoselvitystila.html), I have looked at the handling fees and they all seem to be below 300€.

> .. as any EU citizen can live here for 3 months, no questions asked.

Please note that even 1 word changes the meaning of a statement. In the guide, it's been written:

> If you're a EU citizen, as the target audience of this guide is people who are already living in Finland for **MORE** than 3 months, given that you have **ALREADY** registered your right of residence, you don't need to apply for another permit.

So, the word **more** here means that the EU citizen has been living here beyond 3 months. And if that's so, they were **obligated** by law to register their right of residence in Finland **WITHIN** those 3 months. Therefore, if they have already registered their residence in Finland within those 3 months, they can change their profession from being an employee to self-employed or do whatever they want, as that's their right. 

And the word **already** also implies that the person has already done that, and therefore they're entitled to Kela benefits. 

> and start my own company and if things fall apart I’ll go to Kela.

They can go to Kela with no problem, if they were fulfilling their mandatory social security obligation by buying YEL insurance.

> oh well, you need to contribute to Kela for a certain period of time (1 year?) before you’re
granted full benefits.

Could you please provide a reference for your claim and specify what you mean exactly by "full benefits"? Certain benefits require a period of contribution before you're entitled to them, like [working for 15 minutes as a `self-employed` person with YEL insurance before being eligible to get unemployment benefits](https://www.kela.fi/web/en/what-is-the-work-requirement-), but that is not relavent to the `Know how to handle your upcoming new immigration status` section we're talking about here.
