### ISSUE TITLE
How can I make money out of this? 😊

### ISSUE THREAD

**Issue by sam-hosseini** [sam-hosseini/freelancing-in-finland#26]
Ciao fellow freelancers (or to-be-freelancers)! 👋  Here's a meme to open the discussion :)

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/6043781/73599392-be8d0c80-454b-11ea-88fe-0b79ea27cd2b.png">

### What were my motivations when writing this guide?

Both selfish and selfless reasons.

I had written that, ff58445eae35c0737a27d5c47d1e46ba3a400e5c, long before I launch this guide on [reddit](https://www.reddit.com/r/Finland/comments/euq1wa/ive_spent_50_hours_writing_a_public_guide_about/), [Hacker News](https://news.ycombinator.com/item?id=22190956) or [Twitter](https://twitter.com/sam_hosseini_/status/1221739116842319872).

Therefore, it was **never out of pure goodwill only** and I'm not claiming "I'm a good person" who *just wants to help the community*, as I myself find it hard to trust anyone who says that unless they have absolute financial independence. I don't have that absolute financial independence and therefore I need to make money in life, 47f59875121a6c51c6760c2422b0a76bb72dcff2, simple as that :)

### What are the things my friends and this guide's fans have told me to do already?

**1) To make a Slack community exclusively for software developers who are freelancers or want to become one**.

No sales people, or any other profession for that matter. Only software developers.

How can I make money out of this?
* You paying to get in the community?
* Me sliding into Slack and `@channel`-ing everyone with advertisements every once in a while? 😁
* I don't know. Do you know? Please let me know!

**2) To organize a 1-to-1/webinar session to help you eliminate your concerns, if any, or validate your thoughts**.

I hate to use the word "coaching" as I need lotsa coaching myself 😄. However, I do know plenty when it comes to this employee-to-freelancer journey, so I can legitly help you with your concerns or validating your thoughts.

How can I make money out of this?
* Me charging you hourly for it?
* Me getting money from freelance brokers if you get a project through them?
    * This is already in progress.
    * I intend to make a deal with freelance brokers in which ALL contributors 🧡 to this guide would have the option to do the referral prograam, not just me.
* I don't know. Do you know? Please let me know!

**3) To get sponsors for the guide**.

A giant banner on top of the guide for maximum visibility for a company that wants to promote their brand and target specifically developers in Finland.

![](https://via.placeholder.com/900x200?text=SponsorCompanyLogoHere)

How can I make money out of this?
* Me charging them a monthly fee for the banner?
* I don't know. Do you know? Please let me know!

**4) To write a book** 😲.

I'm not convinced with this one myself 😁 My issue with writing a book is that I wanna know why would anyone be interested in a book when the guide is already organized, compact, and has all the info? 🤔 Or what kind of information would people be willing to know that maybe a book would be a better format for? 

How can I make money out of this?
* Me charging you for pre-orders of book and collecting pre-order-people's-wishes and writing a book about it?
* I don't know. Do you know? Please let me know!

### Can you share your thoughts on how I can do it?
Thank you :)

**Comment by sam-hosseini** [comment]
Small popularity voting poll (vote with emojis):

1) Slack community => ❤️
2) 1-to-1/webinar session => 👍🏼
3) Sponsor logo => 🚀
4) A book => 🎊

**Comment by sam-hosseini** [comment]
Closing based on 4230c50

**Comment by Keksike** [comment]
Hi @sam-hosseini,

I ended up in this issue from the README.md, when I was helping a friend of mine who is considering freelancing.

I was wondering, are you still open for sponsorships, or did you ditch the idea? Our company [Rare](rare.fi) might be interested in sponsoring your great guide in exchange for a banner on the readme :)

Best regards,
Cihan

**Comment by sam-hosseini** [comment]
Hi @Keksike,

Yes I'm still open to sponsorships 👍🏼 and sure, I'll send an email to your rare.fi email address so we can start the discussion.

Thanks! 🍁

**Comment by vladwalross** [comment]
@sam-hosseini wouldn’t this be a violation to the acceptable usage terms?

**Comment by sam-hosseini** [comment]
> @sam-hosseini wouldn’t **this** be a violation to **the** acceptable usage terms?

@vladwalross by **this**, what are you referring to? by **the**, which terms are you referring to?

**Comment by vladwalross** [comment]
Sponsorship.

https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-acceptable-use-policies

**Comment by sam-hosseini** [comment]
> Sponsorship.
> 
> https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-acceptable-use-policies

On their [Advertising on GitHub](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-acceptable-use-policies#8-advertising-on-github):

> While we understand that you may want to promote your Content by posting supporters' names or logos in your Account, **the primary focus of the Content posted in or through your Account to the Service should not be advertising or promotional marketing.**

The primary focus of this repository is not the sponsorship logo, it's the freelancing content within it. This is evidently the case because until today, there hasn't been any sponsorship logo in the guide and I've been maintaining this guide for free for around 1 year in my free time. There are plenty of other repositories that put the logo of their sponsors in their repositories (like [Faker.js](https://github.com/Marak/faker.js#backers)) as well, so this is a common practice. Therefore, I don't think it's in violation of github terms.

**Comment by vladwalross** [comment]
Nice! I just pop up the question because I wasn’t sure how it works (I didn’t read the terms) and want to ask if you were aware.
