### ISSUE TITLE
I would propably add 'I'm not a lawyer, use this at your own risk' notice

### ISSUE THREAD

**Issue by onnimonni** [sam-hosseini/freelancing-in-finland#3]
Hey!

Thanks for this really exhaustive list.

In Finland you probably can make any statements you like without worrying about somebody suing you.

I would still probably want to protect myself if I were you. So mentioning that people will use this list with their own risk might be a good idea. If you have your own corporate lawyer who has reviewed this document then go ahead 👍.

I'm not sure if few parts of this tutorial are correct for companies including only one person. For example the massage. It's true that companies can provide massage benefit for all of their employees but it's little iffy for one man companies. If you can add a source for this information it would be great.

**Comment by sam-hosseini** [comment]
Hello!

My pleasure :)

> In Finland you probably can make any statements you like without worrying about somebody suing you.
I would still probably want to protect myself if I were you. So mentioning that people will use this list with their own risk might be a good idea. If you have your own corporate lawyer who has reviewed this document then go ahead 👍.

You're right, it doesn't hurt to be explicit about the legal matters. Done in 0df0bbf5c605fbac0073bf55885cb7fbdc421e4b 👍 

> I'm not sure if few parts of this tutorial are correct for companies including only one person. For example the massage. It's true that companies can provide massage benefit for all of their employees but it's little iffy for one man companies. If you can add a source for this information it would be great.

I have a one-person company and majority of the info written in this guide are what I've first hand experienced. For the massage benefit, I added it to the list even though I personally haven't taken it for myself. I had put my reasoning based on [Smartum page](https://www.smartum.fi/en/tuotteet/) which said the following about lunch benefit:

> The size of your company is not a factor when it comes to the lunch benefit. The Smartum Lunch benefit is available to all limited companies, even if you are the only employee. You must eat, too, right?

So based on that, I generalized it to all other benefits, including massage, which might be wrong.

One other reason behind my decision was that in my thinking, it would be unfair towards one-person companies if they cannot offer themselves massage benefit compared to bigger companies, and I relied on my intuition developed in ~7 years in Finland which would tell me "that cannot be the case". But I'm not the *source of truth* for it, Vero is, and I might be wrong here as well :)

However, if I were to be leaning on the more-cautious side, I probably wouldn't have been able to write most of the content in this guide. That's the reason why I have included **Source of truth** for every section, which would imply that the info could very well be wrong and the reader should refer to **source of truth** for the most up-to-date and reliable information.

If you let me know which other parts you think are not correct for one-person companies, I'd be glad to clarify it as well 😊

**Comment by onnimonni** [comment]
> You're right, it doesn't hurt to be explicit about the legal matters. Done in 0df0bbf 👍

Excellent. This is probably a little overcautious but it's better this way.

> One other reason behind my decision was that in my thinking, it would be unfair towards one-person companies if they cannot offer themselves massage benefit compared to bigger companies, and I relied on my intuition developed in ~7 years in Finland which would tell me "that cannot be the case". But I'm not the source of truth for it, Vero is, and I might be wrong here as well :)

There are few weird parts of the Finnish tax legislation which are not explicit and the tax office can and probably will view massage benefit as disguised dividend to the owner. And if they do tax investigation I propably wouldn't want to have massage benefits in my books as a sole owner of my company.

These few pages that I googled about accounting [1] & [2] (in finnish) mention that one man company can't give massage benefit for the sole owner. They recommend you to ask **preliminary ruling** from the tax office. If the tax office responds that it's okay then it's legally binding and you can have as many massages as you want.

Preliminary rulings cost 980€ [3] and they most propably will say no so it might not be worth it.

However if you have a company health care plan designed together with occupational health service and the doctor recommends you to meet a physiologist who does the massage then it's okay. But without the doctor's order they will see it as disguised dividend. Finnish law can be quite weird sometimes 🤷‍♂

Other parts of the tutorial seem great to me but I would remove the massage benefit 👍. You will have enough money from your freelancing to pay for the massage from your own heavily taxed pocket 😄

[1] https://certum.fi/fiksu-pienyrittaja-tuntee-verovahennysvinkit/
[2] https://www.paperiton.info/kavin-hierojalla-voinko-vahentaa-kulun-yrityksen-kirjanpidossa/
[3] https://www.vero.fi/syventavat-vero-ohjeet/ohje-hakusivu/49191/hinnasto_verohallinnon_maksullisista_pa/

**Comment by sam-hosseini** [comment]
@allcontributors add @onnimonni to contributors for doc

**Comment by sam-hosseini** [comment]
> Excellent. This is probably a little overcautious but it's better this way.

💯%

About the massage benefit, you've convinced me and I think it's wise to remove it. Thanks a lot for pointing it out and reducing the risk of complications with Vero for all the readers. Done in 55fb408 👍 

> There are few weird parts of the Finnish tax legislation which are not explicit and the tax office can and probably will view massage benefit as disguised dividend to the owner. And if they do tax investigation I propably wouldn't want to have massage benefits in my books as a sole owner of my company.

I'd like to +1 this. I've talked with several accountants (my own and union's) and lawyers and things seem to be always cloudy ☁️  and in the gray zone, and nobody really knows nor can give a binary answer (it's ok or not ok) and the ultimate authority who will decide is Vero. Even if you call Vero, they redirect you "to an expert" and that expert will further redirect you "to an expert in your industry" and on and on and on. It really is strict and implicit at times, and I do acknowledge I'd do anything not to further complicate it with them as well 👍 

Is there anythhing else you'd like to add? Or shall I close this? :)

**Comment by onnimonni** [comment]
You're welcome! Thanks for making the edit.
