### ISSUE TITLE
The 'Talented' link in the list of brokers is - ironically - broken

### ISSUE THREAD

**Issue by YannickMeeus** [sam-hosseini/freelancing-in-finland#4]
It currently redirects to `https://talented.fi/for-talents/`, but maybe your intention is for it to redirect to `https://talented.fi/en/consultant/`?

**Comment by sam-hosseini** [comment]
Amazing title, I woke up to the notification in the morning and it made me laugh 😄 

Thanks for the heads up. They've renewed their website from the time I wrote that section almost 3 months ago. Done in 88e3a3d 👍

**Comment by YannickMeeus** [comment]
Tangentially, I absolutely love this guide and appreciate both yourself and the work you put into it. Thank you!

**Comment by sam-hosseini** [comment]
Makes me very happy to hear that Yannick, thank you! :)

**Comment by sam-hosseini** [comment]
@allcontributors add @YannickMeeus to contributors for bug

**Comment by sam-hosseini** [comment]
I didn't know back in Jan that bug reports have an emoji-key in All Contributors, sorry for not having added you to the contributors list earlier 🙌🏼 I wish you happy holidays 👍🏼
