### ISSUE TITLE
Review number formats

### ISSUE THREAD

**Issue by vladwalross** [sam-hosseini/freelancing-in-finland#48]
Number formats are inconsistent, sometimes it's a comma for decimal, sometimes it's for thousand separator. Same with dots.

- [X] I have read and taken into account [CONTRIBUTING.md](https://github.com/sam-hosseini/freelancing-in-finland/blob/master/.github/CONTRIBUTING.md) ✨🚀💯

**Comment by sam-hosseini** [comment]
@allcontributors add @vladwalross to contributors for bug

**Comment by sam-hosseini** [comment]
> Number formats are inconsistent, sometimes it's a comma for decimal, sometimes it's for thousand separator. Same with dots.

Great catch! All fixed in the referrenced commit 👍🏼

Thank you for this as well 🙌🏼
