### ISSUE TITLE
payslip for self-employed

### ISSUE THREAD

**Issue by igagis** [sam-hosseini/freelancing-in-finland#54]
In the [Understand your new personal taxation situation](https://github.com/sam-hosseini/freelancing-in-finland#understand-your-new-personal-taxation-situation) section you consider payslips for `employee` and `self-employed`. And for `self-employed` case you state that effectively only individual's income tax is to be payed, while company pays just 1.53% of salary as taxes. Could you clarify a bit, why is `individual` in this case different from `employee`? My understanding was that even if you have founded an Oy, in case you are paying yourself a salary you essentially are an `employee` of your Oy, thus normal `employee` payslip case should apply, isn't it so? What if, as an owner of the Oy I hire another person as `employee`? In that case also normal `employee` payslip should apply, right?

Could you provide some link to official information where it states that owner of Oy can pay himself salary with only 1.53% taxes from company side?

**Comment by igagis** [comment]
do I understand right that you meant the Oy pays its owner salary as trade income?
https://www.vero.fi/en/businesses-and-corporations/about-corporate-taxes/being_an_employer/wages-or-trade-income/

**Comment by sam-hosseini** [comment]
I'm afraid I need to diverge on the topic of discussion.

These days I'm running low on resources of time and energy, something that is worsened by the ~1 year old pandemic we live in. Only today I've spent +2 hours answering the other issue, and this is no longer practical for me.

I'm not able to dedicate more time to answering the questions in `issues` format, so I'm going to disable it right after I post this. But please do join the freelance networks I've mentioned in the guide and ask your question from the brokers or in their Slack channels, there are plenty of helpful people who can help out.

Thank you for understanding 😌
